apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie
  labels:
    app: movie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie
  template:
    metadata:
      labels:
        app: movie
    spec:
      containers:
        - name: movie
          image: cyriltostivint/movie-service:{{ .Values.image.tag }}
          imagePullPolicy: IfNotPresent
          command: ["uvicorn"]
          args:
            ["app.main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]
          env:
            - name: DATABASE_URI
              value: postgresql://movie_db_username:movie_db_password@movie-db/movie_db_dev
            - name: CAST_SERVICE_HOST_URL
              value: http://cast_service:8000/api/v1/casts/
          ports:
            - containerPort: 8000
              name: movie
